name: Build and package RoBERTa-sequencing to Dockerhub
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: upgrade az cli
      run: sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli

    - name: set auto-install of extensions
      run: az config set auto-upgrade.prompt=no
      
    - name: workaround, auto extension upgrade does not work
      run: az extension add --name ml
      
    - name: attach workspace
      if: ${{ false }}
      run: az ml folder attach --workspace-name "mlops-dev" --resource-group "learn-mlops"

    - name: retrieve the model
      run: az ml model download --name roberta-sequence --version 1 --download-path . --resource-group learn-mlops --workspace-name mlops-dev
 
    - name: Authenticate to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: welmsdev/flask-roberta:latest
